### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [enrico9034/zsh-watch-plugin#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by enrico9034** [comment]
I add the LICENSE file.
Thank you so much

**Comment by unixorn** [comment]
Thanks!
